#!/usr/bin/env bash

# Use this script to easily create a new project with a GH repo automatically tied it (action == 0)
# Can also be used to automatically tie in a sandbox Heroku Node server and create a new Node-Express project (action == 1)

# How to use: $ bash supercreate dirName action

if [ $# -gt 1 ]
then

	# Just create new directory and new GH repo
	if [ $2 == '0' ]
	then
	  echo "Creating GH repo"
		mkdir $1
		cd $1
		curl -u 'whittlbc' https://api.github.com/user/repos -d '{"name":"'$1'"}'
		git init
		touch README.md
		git add README.md
		git commit -m "first commit"
		git remote add origin 'https://github.com/whittlbc/'$1'.git'
		git push -u origin master		
		echo "Successfully created new GH repo!"
	fi

	# Create new directory, new GH repo, new Node-Express app, and new sandbox Heroku Node server
	if [ $2 == '1' ]
	then
	  echo "Creating GH repo, sandbox Heroku server, and Node/Express app"
		express $1
		cd $1
		curl -u 'whittlbc' https://api.github.com/user/repos -d '{"name":"'$1'"}'
		touch README.md
		echo "web: node app.js" >> Procfile
		echo "/node_modules" >> .gitignore
		npm install
		git init
		git add -A .
		git commit -m "first commit"
		git remote add origin 'https://github.com/whittlbc/'$1'.git'
		git push -u origin master		
		heroku create
		git push heroku master
		heroku ps:scale web=1
		echo "Successfully created new GH repo, sandbox Heroku server, and Node-Express app!"
	fi
fi



